nowplaying:
  restart: always
  build: nowplaying
  env_file: .env
  ports:
    - 8002:80
statistics-logger:
  restart: always
  build: statistics-logger
  environment:
    STAT_LOG_PATH: /var/log/icestats
  volumes:
    - /var/log/icestats:/var/log/icestats
