statistics-logger:
  restart: always
  build: statistics-logger
  environment:
    STAT_LOG_PATH: /var/log/icestats
  volumes:
    - /var/log/icestats:/var/log/icestats
redis:
  restart: always
  image: redis
